/**
 *
 *  Chapter.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Chapter.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon_model::novel;

const std::string Chapter::Cols::_Chapter_ID = "Chapter_ID";
const std::string Chapter::Cols::_Book_ID = "Book_ID";
const std::string Chapter::Cols::_Part_Num = "Part_Num";
const std::string Chapter::Cols::_Chapter_Num = "Chapter_Num";
const std::string Chapter::Cols::_Title = "Title";
const std::string Chapter::Cols::_User_ID = "User_ID";
const std::string Chapter::Cols::_Valid = "Valid";
const std::string Chapter::Cols::_Content = "Content";
const std::string Chapter::Cols::_Memo = "Memo";
const std::string Chapter::primaryKeyName = "Chapter_ID";
const bool Chapter::hasPrimaryKey = true;
const std::string Chapter::tableName = "chapter";

const std::vector<typename Chapter::MetaData> Chapter::metaData_={
{"Chapter_ID","int32_t","int(10)",4,1,1,1},
{"Book_ID","int32_t","int(10)",4,0,0,1},
{"Part_Num","int32_t","int(10)",4,0,0,1},
{"Chapter_Num","int32_t","int(10)",4,0,0,1},
{"Title","std::string","varchar(255)",255,0,0,1},
{"User_ID","int32_t","int(10)",4,0,0,1},
{"Valid","int8_t","tinyint(1)",1,0,0,1},
{"Content","std::string","text",0,0,0,1},
{"Memo","std::string","text",0,0,0,1}
};
const std::string &Chapter::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Chapter::Chapter(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["Chapter_ID"].isNull())
        {
            chapterId_=std::make_shared<int32_t>(r["Chapter_ID"].as<int32_t>());
        }
        if(!r["Book_ID"].isNull())
        {
            bookId_=std::make_shared<int32_t>(r["Book_ID"].as<int32_t>());
        }
        if(!r["Part_Num"].isNull())
        {
            partNum_=std::make_shared<int32_t>(r["Part_Num"].as<int32_t>());
        }
        if(!r["Chapter_Num"].isNull())
        {
            chapterNum_=std::make_shared<int32_t>(r["Chapter_Num"].as<int32_t>());
        }
        if(!r["Title"].isNull())
        {
            title_=std::make_shared<std::string>(r["Title"].as<std::string>());
        }
        if(!r["User_ID"].isNull())
        {
            userId_=std::make_shared<int32_t>(r["User_ID"].as<int32_t>());
        }
        if(!r["Valid"].isNull())
        {
            valid_=std::make_shared<int8_t>(r["Valid"].as<int8_t>());
        }
        if(!r["Content"].isNull())
        {
            content_=std::make_shared<std::string>(r["Content"].as<std::string>());
        }
        if(!r["Memo"].isNull())
        {
            memo_=std::make_shared<std::string>(r["Memo"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 9 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            chapterId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            bookId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            partNum_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            chapterNum_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            title_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            userId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            valid_=std::make_shared<int8_t>(r[index].as<int8_t>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            content_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            memo_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Chapter::Chapter(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 9)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            chapterId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            bookId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            partNum_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            chapterNum_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            title_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            valid_=std::make_shared<int8_t>((int8_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            content_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            memo_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
}

Chapter::Chapter(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("Chapter_ID"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["Chapter_ID"].isNull())
        {
            chapterId_=std::make_shared<int32_t>((int32_t)pJson["Chapter_ID"].asInt64());
        }
    }
    if(pJson.isMember("Book_ID"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["Book_ID"].isNull())
        {
            bookId_=std::make_shared<int32_t>((int32_t)pJson["Book_ID"].asInt64());
        }
    }
    if(pJson.isMember("Part_Num"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["Part_Num"].isNull())
        {
            partNum_=std::make_shared<int32_t>((int32_t)pJson["Part_Num"].asInt64());
        }
    }
    if(pJson.isMember("Chapter_Num"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["Chapter_Num"].isNull())
        {
            chapterNum_=std::make_shared<int32_t>((int32_t)pJson["Chapter_Num"].asInt64());
        }
    }
    if(pJson.isMember("Title"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["Title"].isNull())
        {
            title_=std::make_shared<std::string>(pJson["Title"].asString());
        }
    }
    if(pJson.isMember("User_ID"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["User_ID"].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson["User_ID"].asInt64());
        }
    }
    if(pJson.isMember("Valid"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["Valid"].isNull())
        {
            valid_=std::make_shared<int8_t>((int8_t)pJson["Valid"].asInt64());
        }
    }
    if(pJson.isMember("Content"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["Content"].isNull())
        {
            content_=std::make_shared<std::string>(pJson["Content"].asString());
        }
    }
    if(pJson.isMember("Memo"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["Memo"].isNull())
        {
            memo_=std::make_shared<std::string>(pJson["Memo"].asString());
        }
    }
}

void Chapter::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 9)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            chapterId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            bookId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            partNum_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            chapterNum_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            title_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            valid_=std::make_shared<int8_t>((int8_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            content_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            memo_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
}
                                                                    
void Chapter::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("Chapter_ID"))
    {
        if(!pJson["Chapter_ID"].isNull())
        {
            chapterId_=std::make_shared<int32_t>((int32_t)pJson["Chapter_ID"].asInt64());
        }
    }
    if(pJson.isMember("Book_ID"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["Book_ID"].isNull())
        {
            bookId_=std::make_shared<int32_t>((int32_t)pJson["Book_ID"].asInt64());
        }
    }
    if(pJson.isMember("Part_Num"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["Part_Num"].isNull())
        {
            partNum_=std::make_shared<int32_t>((int32_t)pJson["Part_Num"].asInt64());
        }
    }
    if(pJson.isMember("Chapter_Num"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["Chapter_Num"].isNull())
        {
            chapterNum_=std::make_shared<int32_t>((int32_t)pJson["Chapter_Num"].asInt64());
        }
    }
    if(pJson.isMember("Title"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["Title"].isNull())
        {
            title_=std::make_shared<std::string>(pJson["Title"].asString());
        }
    }
    if(pJson.isMember("User_ID"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["User_ID"].isNull())
        {
            userId_=std::make_shared<int32_t>((int32_t)pJson["User_ID"].asInt64());
        }
    }
    if(pJson.isMember("Valid"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["Valid"].isNull())
        {
            valid_=std::make_shared<int8_t>((int8_t)pJson["Valid"].asInt64());
        }
    }
    if(pJson.isMember("Content"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["Content"].isNull())
        {
            content_=std::make_shared<std::string>(pJson["Content"].asString());
        }
    }
    if(pJson.isMember("Memo"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["Memo"].isNull())
        {
            memo_=std::make_shared<std::string>(pJson["Memo"].asString());
        }
    }
}

const int32_t &Chapter::getValueOfChapterId() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(chapterId_)
        return *chapterId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Chapter::getChapterId() const noexcept
{
    return chapterId_;
}
void Chapter::setChapterId(const int32_t &pChapterId) noexcept
{
    chapterId_ = std::make_shared<int32_t>(pChapterId);
    dirtyFlag_[0] = true;
}
const typename Chapter::PrimaryKeyType & Chapter::getPrimaryKey() const
{
    assert(chapterId_);
    return *chapterId_;
}

const int32_t &Chapter::getValueOfBookId() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(bookId_)
        return *bookId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Chapter::getBookId() const noexcept
{
    return bookId_;
}
void Chapter::setBookId(const int32_t &pBookId) noexcept
{
    bookId_ = std::make_shared<int32_t>(pBookId);
    dirtyFlag_[1] = true;
}

const int32_t &Chapter::getValueOfPartNum() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(partNum_)
        return *partNum_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Chapter::getPartNum() const noexcept
{
    return partNum_;
}
void Chapter::setPartNum(const int32_t &pPartNum) noexcept
{
    partNum_ = std::make_shared<int32_t>(pPartNum);
    dirtyFlag_[2] = true;
}

const int32_t &Chapter::getValueOfChapterNum() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(chapterNum_)
        return *chapterNum_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Chapter::getChapterNum() const noexcept
{
    return chapterNum_;
}
void Chapter::setChapterNum(const int32_t &pChapterNum) noexcept
{
    chapterNum_ = std::make_shared<int32_t>(pChapterNum);
    dirtyFlag_[3] = true;
}

const std::string &Chapter::getValueOfTitle() const noexcept
{
    const static std::string defaultValue = std::string();
    if(title_)
        return *title_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Chapter::getTitle() const noexcept
{
    return title_;
}
void Chapter::setTitle(const std::string &pTitle) noexcept
{
    title_ = std::make_shared<std::string>(pTitle);
    dirtyFlag_[4] = true;
}
void Chapter::setTitle(std::string &&pTitle) noexcept
{
    title_ = std::make_shared<std::string>(std::move(pTitle));
    dirtyFlag_[4] = true;
}

const int32_t &Chapter::getValueOfUserId() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(userId_)
        return *userId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Chapter::getUserId() const noexcept
{
    return userId_;
}
void Chapter::setUserId(const int32_t &pUserId) noexcept
{
    userId_ = std::make_shared<int32_t>(pUserId);
    dirtyFlag_[5] = true;
}

const int8_t &Chapter::getValueOfValid() const noexcept
{
    const static int8_t defaultValue = int8_t();
    if(valid_)
        return *valid_;
    return defaultValue;
}
const std::shared_ptr<int8_t> &Chapter::getValid() const noexcept
{
    return valid_;
}
void Chapter::setValid(const int8_t &pValid) noexcept
{
    valid_ = std::make_shared<int8_t>(pValid);
    dirtyFlag_[6] = true;
}

const std::string &Chapter::getValueOfContent() const noexcept
{
    const static std::string defaultValue = std::string();
    if(content_)
        return *content_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Chapter::getContent() const noexcept
{
    return content_;
}
void Chapter::setContent(const std::string &pContent) noexcept
{
    content_ = std::make_shared<std::string>(pContent);
    dirtyFlag_[7] = true;
}
void Chapter::setContent(std::string &&pContent) noexcept
{
    content_ = std::make_shared<std::string>(std::move(pContent));
    dirtyFlag_[7] = true;
}

const std::string &Chapter::getValueOfMemo() const noexcept
{
    const static std::string defaultValue = std::string();
    if(memo_)
        return *memo_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Chapter::getMemo() const noexcept
{
    return memo_;
}
void Chapter::setMemo(const std::string &pMemo) noexcept
{
    memo_ = std::make_shared<std::string>(pMemo);
    dirtyFlag_[8] = true;
}
void Chapter::setMemo(std::string &&pMemo) noexcept
{
    memo_ = std::make_shared<std::string>(std::move(pMemo));
    dirtyFlag_[8] = true;
}

void Chapter::updateId(const uint64_t id)
{
    chapterId_ = std::make_shared<int32_t>(static_cast<int32_t>(id));
}

const std::vector<std::string> &Chapter::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "Book_ID",
        "Part_Num",
        "Chapter_Num",
        "Title",
        "User_ID",
        "Valid",
        "Content",
        "Memo"
    };
    return inCols;
}

void Chapter::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getBookId())
        {
            binder << getValueOfBookId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getPartNum())
        {
            binder << getValueOfPartNum();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getChapterNum())
        {
            binder << getValueOfChapterNum();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getTitle())
        {
            binder << getValueOfTitle();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getValid())
        {
            binder << getValueOfValid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getContent())
        {
            binder << getValueOfContent();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getMemo())
        {
            binder << getValueOfMemo();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Chapter::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    return ret;
}

void Chapter::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getBookId())
        {
            binder << getValueOfBookId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getPartNum())
        {
            binder << getValueOfPartNum();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getChapterNum())
        {
            binder << getValueOfChapterNum();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getTitle())
        {
            binder << getValueOfTitle();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getValid())
        {
            binder << getValueOfValid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getContent())
        {
            binder << getValueOfContent();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getMemo())
        {
            binder << getValueOfMemo();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Chapter::toJson() const
{
    Json::Value ret;
    if(getChapterId())
    {
        ret["Chapter_ID"]=getValueOfChapterId();
    }
    else
    {
        ret["Chapter_ID"]=Json::Value();
    }
    if(getBookId())
    {
        ret["Book_ID"]=getValueOfBookId();
    }
    else
    {
        ret["Book_ID"]=Json::Value();
    }
    if(getPartNum())
    {
        ret["Part_Num"]=getValueOfPartNum();
    }
    else
    {
        ret["Part_Num"]=Json::Value();
    }
    if(getChapterNum())
    {
        ret["Chapter_Num"]=getValueOfChapterNum();
    }
    else
    {
        ret["Chapter_Num"]=Json::Value();
    }
    if(getTitle())
    {
        ret["Title"]=getValueOfTitle();
    }
    else
    {
        ret["Title"]=Json::Value();
    }
    if(getUserId())
    {
        ret["User_ID"]=getValueOfUserId();
    }
    else
    {
        ret["User_ID"]=Json::Value();
    }
    if(getValid())
    {
        ret["Valid"]=getValueOfValid();
    }
    else
    {
        ret["Valid"]=Json::Value();
    }
    if(getContent())
    {
        ret["Content"]=getValueOfContent();
    }
    else
    {
        ret["Content"]=Json::Value();
    }
    if(getMemo())
    {
        ret["Memo"]=getValueOfMemo();
    }
    else
    {
        ret["Memo"]=Json::Value();
    }
    return ret;
}

Json::Value Chapter::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 9)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getChapterId())
            {
                ret[pMasqueradingVector[0]]=getValueOfChapterId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getBookId())
            {
                ret[pMasqueradingVector[1]]=getValueOfBookId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getPartNum())
            {
                ret[pMasqueradingVector[2]]=getValueOfPartNum();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getChapterNum())
            {
                ret[pMasqueradingVector[3]]=getValueOfChapterNum();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getTitle())
            {
                ret[pMasqueradingVector[4]]=getValueOfTitle();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getUserId())
            {
                ret[pMasqueradingVector[5]]=getValueOfUserId();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getValid())
            {
                ret[pMasqueradingVector[6]]=getValueOfValid();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getContent())
            {
                ret[pMasqueradingVector[7]]=getValueOfContent();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getMemo())
            {
                ret[pMasqueradingVector[8]]=getValueOfMemo();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getChapterId())
    {
        ret["Chapter_ID"]=getValueOfChapterId();
    }
    else
    {
        ret["Chapter_ID"]=Json::Value();
    }
    if(getBookId())
    {
        ret["Book_ID"]=getValueOfBookId();
    }
    else
    {
        ret["Book_ID"]=Json::Value();
    }
    if(getPartNum())
    {
        ret["Part_Num"]=getValueOfPartNum();
    }
    else
    {
        ret["Part_Num"]=Json::Value();
    }
    if(getChapterNum())
    {
        ret["Chapter_Num"]=getValueOfChapterNum();
    }
    else
    {
        ret["Chapter_Num"]=Json::Value();
    }
    if(getTitle())
    {
        ret["Title"]=getValueOfTitle();
    }
    else
    {
        ret["Title"]=Json::Value();
    }
    if(getUserId())
    {
        ret["User_ID"]=getValueOfUserId();
    }
    else
    {
        ret["User_ID"]=Json::Value();
    }
    if(getValid())
    {
        ret["Valid"]=getValueOfValid();
    }
    else
    {
        ret["Valid"]=Json::Value();
    }
    if(getContent())
    {
        ret["Content"]=getValueOfContent();
    }
    else
    {
        ret["Content"]=Json::Value();
    }
    if(getMemo())
    {
        ret["Memo"]=getValueOfMemo();
    }
    else
    {
        ret["Memo"]=Json::Value();
    }
    return ret;
}

bool Chapter::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("Chapter_ID"))
    {
        if(!validJsonOfField(0, "Chapter_ID", pJson["Chapter_ID"], err, true))
            return false;
    }
    if(pJson.isMember("Book_ID"))
    {
        if(!validJsonOfField(1, "Book_ID", pJson["Book_ID"], err, true))
            return false;
    }
    else
    {
        err="The Book_ID column cannot be null";
        return false;
    }
    if(pJson.isMember("Part_Num"))
    {
        if(!validJsonOfField(2, "Part_Num", pJson["Part_Num"], err, true))
            return false;
    }
    else
    {
        err="The Part_Num column cannot be null";
        return false;
    }
    if(pJson.isMember("Chapter_Num"))
    {
        if(!validJsonOfField(3, "Chapter_Num", pJson["Chapter_Num"], err, true))
            return false;
    }
    else
    {
        err="The Chapter_Num column cannot be null";
        return false;
    }
    if(pJson.isMember("Title"))
    {
        if(!validJsonOfField(4, "Title", pJson["Title"], err, true))
            return false;
    }
    else
    {
        err="The Title column cannot be null";
        return false;
    }
    if(pJson.isMember("User_ID"))
    {
        if(!validJsonOfField(5, "User_ID", pJson["User_ID"], err, true))
            return false;
    }
    else
    {
        err="The User_ID column cannot be null";
        return false;
    }
    if(pJson.isMember("Valid"))
    {
        if(!validJsonOfField(6, "Valid", pJson["Valid"], err, true))
            return false;
    }
    else
    {
        err="The Valid column cannot be null";
        return false;
    }
    if(pJson.isMember("Content"))
    {
        if(!validJsonOfField(7, "Content", pJson["Content"], err, true))
            return false;
    }
    else
    {
        err="The Content column cannot be null";
        return false;
    }
    if(pJson.isMember("Memo"))
    {
        if(!validJsonOfField(8, "Memo", pJson["Memo"], err, true))
            return false;
    }
    else
    {
        err="The Memo column cannot be null";
        return false;
    }
    return true;
}
bool Chapter::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 9)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[5] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[6] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[7] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[8] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e) 
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Chapter::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("Chapter_ID"))
    {
        if(!validJsonOfField(0, "Chapter_ID", pJson["Chapter_ID"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("Book_ID"))
    {
        if(!validJsonOfField(1, "Book_ID", pJson["Book_ID"], err, false))
            return false;
    }
    if(pJson.isMember("Part_Num"))
    {
        if(!validJsonOfField(2, "Part_Num", pJson["Part_Num"], err, false))
            return false;
    }
    if(pJson.isMember("Chapter_Num"))
    {
        if(!validJsonOfField(3, "Chapter_Num", pJson["Chapter_Num"], err, false))
            return false;
    }
    if(pJson.isMember("Title"))
    {
        if(!validJsonOfField(4, "Title", pJson["Title"], err, false))
            return false;
    }
    if(pJson.isMember("User_ID"))
    {
        if(!validJsonOfField(5, "User_ID", pJson["User_ID"], err, false))
            return false;
    }
    if(pJson.isMember("Valid"))
    {
        if(!validJsonOfField(6, "Valid", pJson["Valid"], err, false))
            return false;
    }
    if(pJson.isMember("Content"))
    {
        if(!validJsonOfField(7, "Content", pJson["Content"], err, false))
            return false;
    }
    if(pJson.isMember("Memo"))
    {
        if(!validJsonOfField(8, "Memo", pJson["Memo"], err, false))
            return false;
    }
    return true;
}
bool Chapter::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 9)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e) 
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Chapter::validJsonOfField(size_t index,
                               const std::string &fieldName,
                               const Json::Value &pJson, 
                               std::string &err, 
                               bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }        
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;                
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;               
            }

            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;                
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;                
            }
            break;
     
        default:
            err="Internal error in the server";
            return false;
            break;
    }
    return true;
}
