/**
 *
 *  Chapter.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

using namespace drogon::orm;
namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace novel 
{

class Chapter
{
  public:
    struct Cols
    {
        static const std::string _Chapter_ID;
        static const std::string _Book_ID;
        static const std::string _Part_Num;
        static const std::string _Chapter_Num;
        static const std::string _Title;
        static const std::string _User_ID;
        static const std::string _Valid;
        static const std::string _Content;
        static const std::string _Memo;
    };

    const static int primaryKeyNumber;
    const static std::string tableName;
    const static bool hasPrimaryKey;
    const static std::string primaryKeyName;
    using PrimaryKeyType = int32_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names, 
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all 
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Chapter(const Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Chapter(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Chapter(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Chapter() = default;
    
    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson, 
                          std::string &err, 
                          bool isForCreation);

    /**  For column Chapter_ID  */
    ///Get the value of the column Chapter_ID, returns the default value if the column is null
    const int32_t &getValueOfChapterId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getChapterId() const noexcept;
    ///Set the value of the column Chapter_ID
    void setChapterId(const int32_t &pChapterId) noexcept;

    /**  For column Book_ID  */
    ///Get the value of the column Book_ID, returns the default value if the column is null
    const int32_t &getValueOfBookId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getBookId() const noexcept;
    ///Set the value of the column Book_ID
    void setBookId(const int32_t &pBookId) noexcept;

    /**  For column Part_Num  */
    ///Get the value of the column Part_Num, returns the default value if the column is null
    const int32_t &getValueOfPartNum() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getPartNum() const noexcept;
    ///Set the value of the column Part_Num
    void setPartNum(const int32_t &pPartNum) noexcept;

    /**  For column Chapter_Num  */
    ///Get the value of the column Chapter_Num, returns the default value if the column is null
    const int32_t &getValueOfChapterNum() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getChapterNum() const noexcept;
    ///Set the value of the column Chapter_Num
    void setChapterNum(const int32_t &pChapterNum) noexcept;

    /**  For column Title  */
    ///Get the value of the column Title, returns the default value if the column is null
    const std::string &getValueOfTitle() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTitle() const noexcept;
    ///Set the value of the column Title
    void setTitle(const std::string &pTitle) noexcept;
    void setTitle(std::string &&pTitle) noexcept;

    /**  For column User_ID  */
    ///Get the value of the column User_ID, returns the default value if the column is null
    const int32_t &getValueOfUserId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getUserId() const noexcept;
    ///Set the value of the column User_ID
    void setUserId(const int32_t &pUserId) noexcept;

    /**  For column Valid  */
    ///Get the value of the column Valid, returns the default value if the column is null
    const int8_t &getValueOfValid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int8_t> &getValid() const noexcept;
    ///Set the value of the column Valid
    void setValid(const int8_t &pValid) noexcept;

    /**  For column Content  */
    ///Get the value of the column Content, returns the default value if the column is null
    const std::string &getValueOfContent() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getContent() const noexcept;
    ///Set the value of the column Content
    void setContent(const std::string &pContent) noexcept;
    void setContent(std::string &&pContent) noexcept;

    /**  For column Memo  */
    ///Get the value of the column Memo, returns the default value if the column is null
    const std::string &getValueOfMemo() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getMemo() const noexcept;
    ///Set the value of the column Memo
    void setMemo(const std::string &pMemo) noexcept;
    void setMemo(std::string &&pMemo) noexcept;


    static size_t getColumnNumber() noexcept {  return 9;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend Mapper<Chapter>;
#ifdef __cpp_impl_coroutine
    friend CoroMapper<Chapter>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int32_t> chapterId_;
    std::shared_ptr<int32_t> bookId_;
    std::shared_ptr<int32_t> partNum_;
    std::shared_ptr<int32_t> chapterNum_;
    std::shared_ptr<std::string> title_;
    std::shared_ptr<int32_t> userId_;
    std::shared_ptr<int8_t> valid_;
    std::shared_ptr<std::string> content_;
    std::shared_ptr<std::string> memo_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[9]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where Chapter_ID = ?";
        return sql;                   
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where Chapter_ID = ?";
        return sql;                   
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "Chapter_ID,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "Book_ID,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "Part_Num,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "Chapter_Num,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "Title,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "User_ID,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "Valid,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "Content,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "Memo,";
            ++parametersCount;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";
        
        sql +="default,";
        if(dirtyFlag_[1])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[2])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[3])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[4])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[5])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[6])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[7])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[8])
        {
            sql.append("?,");

        } 
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        sql.append(1, ')');
        LOG_TRACE << sql;
        return sql;   
    }
};
} // namespace novel
} // namespace drogon_model
